In [1]:
# importing libraries for data exploration

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Creating dataframe and displaying first 10 rows

df = pd.read_csv("Capstone_2/pollution_data.csv")

df.head(10)

,Date,City,County,State,Population Staying at Home,Population Not Staying at Home,mil_miles,past_week_avg_miles,latitude,longitude,...,pm10_max,pm10_median,pm10_variance,pm10_count,wind-gust_min,wind-gust_max,wind-gust_median,wind-gust_variance,wind-gust_count,pp_feat
0,2019-01-01,albuquerque,bernalillo,NM,"1,77,171","4,99,456",19.038463,0.0,35.107209,-106.617209,...,127.0,18.0,5303.29,48.0,0.3,27.3,3.8,839.84,54.0,0.319492
1,2019-01-01,atlanta,fulton,GA,"2,83,093","7,63,811",29.295609,0.0,33.760109,-84.402826,...,27.0,14.0,280.83,23.0,0.1,4.5,1.7,12.11,44.0,23.304216
2,2019-01-01,austin,travis,TX,"2,68,732","9,76,194",27.286079,0.0,30.283333,-97.750641,...,NaN,NaN,NaN,NaN,0.2,14.0,6.8,162.34,67.0,14.333042
3,2019-01-01,baltimore,baltimo,MD,"1,91,486","4,09,167",12.961132,0.0,39.305833,-76.610417,...,15.0,6.0,74.76,24.0,0.1,24.0,8.5,355.46,70.0,6.403240
4,2019-01-01,boise,ada,ID,"1,05,237","3,63,293",12.640954,0.0,43.604545,-116.202424,...,20.0,5.0,170.86,47.0,0.1,11.3,2.2,46.19,92.0,0.000000
5,2019-01-01,boston,suffolk,MA,"2,64,296","5,40,489",17.221880,0.0,42.351282,-71.062051,...,NaN,NaN,NaN,NaN,2.6,46.0,15.7,1244.66,120.0,86.681580
6,2019-01-01,brooklyn,kings,NY,"9,64,005","16,10,930",52.130628,0.0,40.653269,-73.956538,...,NaN,NaN,NaN,NaN,0.3,33.3,12.2,593.08,88.0,26.824525
7,2019-01-01,charlotte,mecklenburg,NC,"2,63,196","8,27,361",30.960487,0.0,35.196351,-80.828108,...,NaN,NaN,NaN,NaN,0.1,15.1,4.6,173.58,82.0,0.000000
8,2019-01-01,chicago,cook,IL,"13,96,803","37,67,856",148.042151,0.0,41.858851,-87.676437,...,70.0,13.0,2756.66,47.0,0.8,16.5,5.0,84.51,191.0,3.606315
9,2019-01-01,columbia,richland,SC,"89,669","3,23,640",11.010421,0.0,34.011818,-81.013333,...,NaN,NaN,NaN,NaN,0.2,8.2,5.3,66.03,20.0,1.231301

In [3]:
# looping through the array in order to remove the comma
i = 0
while i < len(df['Population Not Staying at Home']):
    df['Population Not Staying at Home'][i] = df['Population Not Staying at Home'][i].replace(",","")
    i += 1

C:\Users\dvisi\AppData\Local\Temp\ipykernel_38140\1481582488.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Population Not Staying at Home'][i] = df['Population Not Staying at Home'][i].replace(",","")

In [4]:
# looping through the array in order to remove the comma
i = 0
while i < len(df['Population Staying at Home']):
    df['Population Staying at Home'][i] = df['Population Staying at Home'][i].replace(",","")
    i += 1

C:\Users\dvisi\AppData\Local\Temp\ipykernel_38140\2078751459.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Population Staying at Home'][i] = df['Population Staying at Home'][i].replace(",","")

In [5]:
# converting the data to numeric and displaying the mean values of each population category
df["Population Not Staying at Home"] = df["Population Not Staying at Home"].astype(int)
df['Population Staying at Home'] = df['Population Staying at Home'].astype(int)
pop_home = df['Population Not Staying at Home'].mean().round(2)
pop_not_home = df['Population Staying at Home'].mean().round(2)

print(f"The mean population for people staying at home is {pop_home} \n")
print(f"The mean population for people staying at home is {pop_not_home} ")

The mean population for people staying at home is 1124679.3

The mean population for people staying at home is 337261.34

In [7]:
df.groupby(['State'])['pm10_count'].mean().round(2)

State
AR       NaN
AZ    192.13
CA     45.98
CO    195.69
CT     46.60
FL    101.39
GA     22.77
HI     45.24
ID     63.36
IL     45.56
IN     22.60
KS       NaN
MA       NaN
MD     22.23
MI     30.88
MN     46.12
MS     38.24
NC     23.18
NE     23.39
NM     62.86
NV    168.05
NY       NaN
OH       NaN
OK     93.24
OR       NaN
PA       NaN
RI       NaN
SC       NaN
TN       NaN
TX    162.11
UT       NaN
VA       NaN
WA       NaN
WI     75.96
Name: pm10_count, dtype: float64