## Parquet <-> CSV and Exercise

### Exercise
1. Generate or copy to this diectory any of the following files:
    1. Extract of any SQL database 
    1. Imported file from your capstone work
    1. Any other data from other exercises you have aleady used
1. Import into Pandas
1. Create at least three new Pandas dataframe outputs ether reproducing prior analytics or new analytics

In [1]:
!head  data.dataset.parquet

'head' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
#be sure to have this notebook in the same folder as your parquet file

#this line of code loads the library into the notebook
import pandas as pd

#this line of code reads the parquet into memory to a Pandas DataFrame 
df = pd.read_parquet('data.dataset.parquet')
df

,age,fnlwgt,education,education-num,marital-status,relationship,race,sex,capital-gain,capital-loss,hours-per-week,income,Scored Labels,Scored Probabilities
0,46,160647,Bachelors,13,Widowed,Unmarried,White,Female,0,0,38,<=50K,<=50K,0.181010
1,60,205934,HS-grad,9,Separated,Not-in-family,White,Female,0,0,25,<=50K,<=50K,0.014068
2,26,195327,HS-grad,9,Never-married,Own-child,White,Male,0,0,40,<=50K,<=50K,0.009978
3,59,184948,Assoc-voc,11,Divorced,Not-in-family,White,Male,0,0,48,<=50K,<=50K,0.190680
4,37,243425,HS-grad,9,Divorced,Other-relative,White,Female,0,0,50,<=50K,<=50K,0.066199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16276,23,265077,Assoc-voc,11,Never-married,Not-in-family,White,Female,0,0,40,<=50K,<=50K,0.004806
16277,41,253060,Bachelors,13,Married-civ-spouse,Husband,White,Male,7688,0,45,>50K,>50K,0.996965
16278,25,143267,HS-grad,9,Never-married,Not-in-family,White,Female,0,0,48,<=50K,<=50K,0.021528
16279,50,21095,Some-college,10,Divorced,Unmarried,Asian-Pac-Islander,Male,0,0,40,<=50K,<=50K,0.091146
16280,54,32778,HS-grad,9,Married-civ-spouse,Wife,White,Female,0,0,30,<=50K,<=50K,0.280434

In [3]:

#this line code exports the data into a format for Power BI
df.to_csv('azureml_export.csv')