%pip install scikit-learn  --upgrade --force
#from sklearn.linear_model import LinearRegression
#from sklearn.model_selection import train_test_split

#### Step-By-Step
###### Step 1: Opening and reading a file.
###### Step 2: Reading a file from different types:   cvs, txt, xlsx ...ect.
###### Step 3: Converting different file types into the dataframe(colums/rows). 
###### Step 4: Verifiy the file headers, data type and data in th columns.
###### Step 5: Filtering and Sorting.




File Options: Reading a file from cvs, txt, xlsx ...ect.

Example:
df = pd.read_csv("mortality_wide.csv" )

for df in pd.read_csv("mortality_wide.csv", chunksize=1000):
print(df)

for df in pd.read_csv("C:/Diff/STROKEDatasets/2016_Mortality_Age35_Plus.csv", chunksize=100):
    print(df)


df = pd.read_csv("mortality_wide.txt, delmiter="\t" )
df = pd.read_csv("mortality_wide.txt, delmiter="xxx" )
df = pd.read_lxsx("mortality_wide.xlsx" )

Stroke_Dataset_2015 = "C:/Diff/STROKEDatasets/2015_Mortality_Age35_Plus.csv"
poke = pd.read_csv(Stroke_Dataset_2015)
print(poke.head())

##### Step 3
Converting different file types into the dataframe(colums/rows). 

Example: Create a dataframe  
df = pd.DataFrame(Stroke_Dataset_2015)
df
 
###### Step 4:
Verifiy the file headers, tails,  data type  ect.

Options to use when analyzing data set:
 #df.tail(2)
 #df.shape  # print rows and columns in tuple.
 #rows, columns = df.shape
 #df.columns # will print all the column names.
 #df.DATE # will print the entire column called "DATE".
 #df[["DATE", "FUEL_COST_PER_GAL" ]]  # print multliple columns as a list.
 #print(df["ColumnName"][0:5]) # print top 5 columns.
 #print(df.ColumnName) # will print a column.
 print(df[["col1", "col2", "col"]])  # create a list of multiple columns and print. 

Options with accessing or getting data in the rows:
 #df[2:5]  # get row 2 - 4.
 #print(df.iloc[1])  get the first index.
 #print(df.iloc[1:4]) get the first - fourth.
 #print(df.iloc[2, 1])   get the value from of the second "[2, 1]" row in the first position or cell of the column.

for index, row in df.iterrows(): # getting or reading row by row. 
    print(index, row)

for index, row in df.iterrows(): # getting or reading row by row. 
    print(index, row["TRIP_METTERS"])

###### Filtering 
Using filter to get specific row that has specific key value
TRIP_METTERS is the column name.

df.loc[df["TRIP_METTERS"] == 250 ]
df.loc[df["TRIP_METTERS"] == "xxxxx"]

###### Sorting - Passing in column names.
ascending=[1,0]
1 means sort the first column asce
0 means sort the second column dece

#df.sort_values("TRIP_METTERS")
df.sort_values("TRIP_METTERS","GALLONS_USED", ascending=False)
df.sort_values(["TRIP_METTERS", "FUEL_COST"])
df.sort_values(["TRIP_METTERS", "FUEL_COST"], ascending=[1,0])

###### Adding Column 

 Adding column using init location
 : means select all rows in the columns
  1:5 means select column 1-5
 sum(axis=1) means adding honzontally 
 sum(axis=0) means adding vertically 

df["TOT"] = df.iloc[:, 1:7].sum(axis=1)
df.head()

In [2]:


# r for reading
# w for writing
# a for pending
# r+ for read and write

f = open ("C:/Diff/test.txt", "w")
print(f.name)
print(f.mode)
f.close()

C:/Diff/test.txt
w

In [3]:
# This method will open and close the file when you leave this block of code. 

with open ("C:/Diff/test.txt", "r+") as f:
    file_contents = f.read()
    print(file_contents)

###  How to creating a dataframe from lists in dictionaries

import os
import pandas as pd 
master_df_01 = pd.DataFrame()

for file in os.listdir(os.getcwd()):
    if file.endswith('.csv'):
        master_df_01 = master_df_01.append(pd.read_csv(file))
        
master_df_01.to_csv('Master_df01.csv', index=False)

In [37]:
import pandas as pd

Milage_Tracker = {
"DATE": ["1/1/2023","1/2/2023","1/3/2023","1/4/2023","1/5/2023" ], 
"FUEL_COST_PER_GAL": [3.00, 3.00, 3.00, 3.00, 3.00 ],
"TRIP_METTERS": [200,200,250,300,315 ],
"MILES_TRAVELED": [20,30,50,50,15 ],
"GALLONS_USED": [2, 2, 4, 4, 1 ],
"FUEL_COST": [4,6, 10, 19,4 ],
"CO_PAYS_PER_MILE": [ .33, .33, .33, .33, .33  ]  
}

df = pd.DataFrame(Milage_Tracker)
df.head() # print the first two rows

,DATE,FUEL_COST_PER_GAL,TRIP_METTERS,MILES_TRAVELED,GALLONS_USED,FUEL_COST,CO_PAYS_PER_MILE
0,1/1/2023,3.0,200,20,2,4,0.33
1,1/2/2023,3.0,200,30,2,6,0.33
2,1/3/2023,3.0,250,50,4,10,0.33
3,1/4/2023,3.0,300,50,4,19,0.33
4,1/5/2023,3.0,315,15,1,4,0.33

In [38]:
type(df.DATE[0])

str

In [39]:
df.dtypes

DATE                  object
FUEL_COST_PER_GAL    float64
TRIP_METTERS           int64
MILES_TRAVELED         int64
GALLONS_USED           int64
FUEL_COST              int64
CO_PAYS_PER_MILE     float64
dtype: object

In [40]:
# change data type from str to date.
pd.to_datetime(df['DATE'])

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
Name: DATE, dtype: datetime64[ns]

In [41]:
for index, row in df.iterrows(): # getting or reading row by row. 
    print(index, row)

0 DATE                 1/1/2023
FUEL_COST_PER_GAL         3.0
TRIP_METTERS              200
MILES_TRAVELED             20
GALLONS_USED                2
FUEL_COST                   4
CO_PAYS_PER_MILE         0.33
Name: 0, dtype: object
1 DATE                 1/2/2023
FUEL_COST_PER_GAL         3.0
TRIP_METTERS              200
MILES_TRAVELED             30
GALLONS_USED                2
FUEL_COST                   6
CO_PAYS_PER_MILE         0.33
Name: 1, dtype: object
2 DATE                 1/3/2023
FUEL_COST_PER_GAL         3.0
TRIP_METTERS              250
MILES_TRAVELED             50
GALLONS_USED                4
FUEL_COST                  10
CO_PAYS_PER_MILE         0.33
Name: 2, dtype: object
3 DATE                 1/4/2023
FUEL_COST_PER_GAL         3.0
TRIP_METTERS              300
MILES_TRAVELED             50
GALLONS_USED                4
FUEL_COST                  19
CO_PAYS_PER_MILE         0.33
Name: 3, dtype: object
4 DATE                 1/5/2023
FUEL_COST_PER_GAL         3.0
TRIP_METTERS              315
MILES_TRAVELED             15
GALLONS_USED                1
FUEL_COST                   4
CO_PAYS_PER_MILE         0.33
Name: 4, dtype: object

In [42]:
for index, row in df.iterrows(): # getting or reading row by row. 
    print(index, row["TRIP_METTERS"])

0 200
1 200
2 250
3 300
4 315

In [43]:
print(df.iloc[2, 1])

3.0

In [44]:
#df.sort_values("TRIP_METTERS")
df.sort_values(["TRIP_METTERS", "FUEL_COST"])

,DATE,FUEL_COST_PER_GAL,TRIP_METTERS,MILES_TRAVELED,GALLONS_USED,FUEL_COST,CO_PAYS_PER_MILE
0,1/1/2023,3.0,200,20,2,4,0.33
1,1/2/2023,3.0,200,30,2,6,0.33
2,1/3/2023,3.0,250,50,4,10,0.33
3,1/4/2023,3.0,300,50,4,19,0.33
4,1/5/2023,3.0,315,15,1,4,0.33

In [45]:
import numpy as np
df.head()

,DATE,FUEL_COST_PER_GAL,TRIP_METTERS,MILES_TRAVELED,GALLONS_USED,FUEL_COST,CO_PAYS_PER_MILE
0,1/1/2023,3.0,200,20,2,4,0.33
1,1/2/2023,3.0,200,30,2,6,0.33
2,1/3/2023,3.0,250,50,4,10,0.33
3,1/4/2023,3.0,300,50,4,19,0.33
4,1/5/2023,3.0,315,15,1,4,0.33

In [46]:
# count number of the same value repeat in a column. 
new_data = df['FUEL_COST'].value_counts()
new_data

4     2
6     1
10    1
19    1
Name: FUEL_COST, dtype: int64

In [47]:
# the length of the unique value in the column is 4.
len(df.TRIP_METTERS.value_counts())

4

In [48]:
# Adding column using init location
# : means select all rows in the columns
#  1:5 means select column 1-5
# sum(axis=1) means adding honzontally 
df["TOT"] = df.iloc[:, 1:7].sum(axis=1)
df.head()

,DATE,FUEL_COST_PER_GAL,TRIP_METTERS,MILES_TRAVELED,GALLONS_USED,FUEL_COST,CO_PAYS_PER_MILE,TOT
0,1/1/2023,3.0,200,20,2,4,0.33,229.33
1,1/2/2023,3.0,200,30,2,6,0.33,241.33
2,1/3/2023,3.0,250,50,4,10,0.33,317.33
3,1/4/2023,3.0,300,50,4,19,0.33,376.33
4,1/5/2023,3.0,315,15,1,4,0.33,338.33

In [58]:
# Sum all values in each column.
#Tot_All= df.iloc[:, 0:5].sum(axis=0)
Tot_All= df.iloc[:, 1:5].sum(axis=0)
Tot_All

FUEL_COST_PER_GAL      15.0
TRIP_METTERS         1265.0
MILES_TRAVELED        165.0
GALLONS_USED           13.0
dtype: float64

In [53]:

import numpy as np
df['Trip_log']= np.log10(df['TRIP_METTERS'])
print(df['Trip_log'])

0    2.301030
1    2.301030
2    2.397940
3    2.477121
4    2.498311
Name: Trip_log, dtype: float64

### Reading files from URL
#### Sample code:

import pandas as pd
poll_url = 'http://projects.fivethirtyeight.com/general-model/president_general_polls_2016.csv'
polls = pd.read_csv(poll_url)
polls

In [49]:
import pandas as pd
poll_url = 'http://projects.fivethirtyeight.com/general-model/president_general_polls_2016.csv'
polls = pd.read_csv(poll_url)
polls

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12619,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,New Hampshire,7/9/2016,7/18/2016,University of New Hampshire,B+,...,40.24983,43.04717,6.924110,NaN,NaN,https://cola.unh.edu/sites/cola.unh.edu/files/...,44650,68189,7/21/16,09:14:14 8 Nov 2016
12620,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Wisconsin,10/21/2016,11/2/2016,Ipsos,A-,...,46.54218,38.96884,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,48259,75560,11/3/16,09:14:14 8 Nov 2016
12621,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,New York,8/7/2016,8/10/2016,Siena College,A,...,53.83622,32.47939,3.881193,NaN,NaN,https://www.siena.edu/assets/files/news/SNY081...,44852,68743,8/15/16,09:14:14 8 Nov 2016
12622,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Virginia,9/30/2016,10/6/2016,Ipsos,A-,...,49.57558,39.96954,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,46675,72969,10/10/16,09:14:14 8 Nov 2016
12623,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Wisconsin,6/9/2016,6/12/2016,Marquette University,A,...,46.40999,39.19839,NaN,NaN,NaN,https://law.marquette.edu/poll/2016/06/15/new-...,44341,66966,6/15/16,09:14:14 8 Nov 2016

### Reading the file stored locally in the c: dir.

In [50]:
import os

In [51]:
# Must change the path -  forward \ to backward / 
import pandas as pd
test = "C:/Diff/Python/Stroke_Project/test.csv"
test = pd.read_csv(test)
test

,Year,LocationAbbr,LocationDesc,GeographicLevel,DataSource,Class,Topic,Data_Value,Data_Value_Unit,Data_Value_Type,...,Data_Value_Footnote,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,TopicID,LocationID,Location 1,Counties,States
0,2015,SD,South Dakota,State,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,Insufficient Data,Gender,Overall,Race/Ethnicity,Black,T6,46,"(44.4332, -100.236)",2679.0,21.0
1,2015,MT,Fergus County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,85.3,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,White,T6,30027,"(47.267076, -109.227158)",2283.0,2.0
2,2015,WV,West Virginia,State,NVSS,Cardiovascular Diseases,Stroke Mortality,83.8,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Male,Race/Ethnicity,White,T6,54,"(38.6411, -80.6147)",2749.0,42.0
3,2015,MN,Minnesota,State,NVSS,Cardiovascular Diseases,Stroke Mortality,94.6,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Female,Race/Ethnicity,Black,T6,27,"(46.3159, -94.3068)",1400.0,1.0
4,2015,MS,Alcorn County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,98.4,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,White,T6,28003,"(34.887179, -88.570153)",396.0,32.0
5,2015,ID,Idaho,State,NVSS,Cardiovascular Diseases,Stroke Mortality,71.9,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Overall,Race/Ethnicity,White,T6,16,"(44.3858, -114.661)",1730.0,5.0
6,2015,MD,Queen Anne's County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,67.8,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,24035,"(39.085562, -76.005396)",423.0,45.0
7,2015,OH,Holmes County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,143.6,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,Black,T6,39075,"(40.560467, -81.923643)",2567.0,38.0
8,2015,WY,Wyoming,State,NVSS,Cardiovascular Diseases,Stroke Mortality,54.4,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Male,Race/Ethnicity,Overall,T6,56,"(42.9984, -107.552)",3084.0,14.0
9,2015,WV,Raleigh County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,89.0,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,White,T6,54081,"(37.76919, -81.24983)",2891.0,42.0
10,2015,OR,Sherman County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,75.9,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,Overall,T6,41055,"(45.397808, -120.68613)",2411.0,12.0
11,2015,IN,Porter County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,63.1,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,Overall,T6,18127,"(41.461832, -87.078064)",164.0,35.0
12,2015,AR,Arkansas,State,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,Insufficient Data,Gender,Male,Race/Ethnicity,Hispanic,T6,5,"(34.8982, -92.434)",998.0,15.0
13,2015,MS,Clay County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,140.8,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,Black,T6,28025,"(33.65729, -88.770796)",1601.0,32.0
14,2015,IL,Peoria County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,83.6,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,17143,"(40.792172, -89.766494)",1757.0,34.0
15,2015,IL,Clay County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,77.4,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,Overall,T6,17025,"(38.758401, -88.495012)",224.0,34.0
16,2015,KS,Saline County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,75.1,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,20169,"(38.77653, -97.644509)",334.0,17.0
17,2015,TX,Texas,State,NVSS,Cardiovascular Diseases,Stroke Mortality,70.8,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Overall,Race/Ethnicity,Hispanic,T6,48,"(31.4906, -99.3517)",3109.0,23.0
18,2015,VA,Bedford County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,88.5,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,Black,T6,51019,"(37.318507, -79.522261)",2754.0,40.0
19,2015,MN,Scott County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,164.8,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,Black,T6,27139,"(44.651138, -93.539207)",1511.0,1.0
20,2015,US,United States,Nation,NVSS,Cardiovascular Diseases,Stroke Mortality,61.0,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Overall,Race/Ethnicity,American Indian and Alaskan Native,T6,0,NaN,NaN,NaN
21,2015,MN,Traverse County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,63.3,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,27155,"(45.772865, -96.473679)",1555.0,1.0
22,2015,PA,Pennsylvania,State,NVSS,Cardiovascular Diseases,Stroke Mortality,70.7,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Male,Race/Ethnicity,White,T6,42,"(40.8749, -77.8022)",2495.0,48.0
23,2015,OR,Harney County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Overall,Race/Ethnicity,Black,T6,41025,"(43.0601, -118.962993)",720.0,12.0
24,2015,AZ,Arizona,State,NVSS,Cardiovascular Diseases,Stroke Mortality,58.4,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Male,Race/Ethnicity,Hispanic,T6,4,"(34.2921, -111.664)",987.0,7.0
25,2015,MD,Maryland,State,NVSS,Cardiovascular Diseases,Stroke Mortality,69.2,"per 100,000 population","Age-adjusted, 3-year Average Rate",...,NaN,Gender,Male,Race/Ethnicity,White,T6,24,"(39.0648, -76.82)",418.0,45.0
26,2015,AL,Coosa County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,108.6,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,Black,T6,1037,"(32.940608, -86.246358)",96.0,29.0
27,2015,GA,Haralson County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,103.7,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,13143,"(33.793278, -85.206781)",186.0,31.0
28,2015,MS,Hinds County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,82.4,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,White,T6,28049,"(32.27193, -90.43907)",1645.0,32.0
29,2015,KY,Fayette County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,70.9,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,21067,"(38.037997, -84.468142)",1230.0,36.0
30,2015,NJ,Salem County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Male,Race/Ethnicity,Asian and Pacific Islander,T6,34033,"(39.583694, -75.351583)",2494.0,46.0
31,2015,ND,McIntosh County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Male,Race/Ethnicity,American Indian and Alaskan Native,T6,38051,"(46.113787, -99.442189)",2419.0,3.0
32,2015,IA,Iowa County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Overall,Race/Ethnicity,American Indian and Alaskan Native,T6,19095,"(41.684583, -92.067097)",284.0,16.0
33,2015,OK,Tulsa County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,77.6,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,Overall,T6,40143,"(36.128351, -95.943357)",2273.0,20.0
34,2015,AL,Autauga County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,108.8,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,Overall,T6,1001,"(32.540743, -86.642658)",90.0,29.0
35,2015,ND,Walsh County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Male,Race/Ethnicity,American Indian and Alaskan Native,T6,38099,"(48.371543, -97.721726)",2468.0,3.0
36,2015,MI,Berrien County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Female,Race/Ethnicity,American Indian and Alaskan Native,T6,26021,"(41.961641, -86.422575)",1216.0,50.0
37,2015,NE,Deuel County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Female,Race/Ethnicity,Hispanic,T6,31049,"(41.107923, -102.330751)",2246.0,19.0
38,2015,OK,Logan County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,108.9,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,Black,T6,40083,"(35.921591, -97.441304)",2201.0,20.0
39,2015,MS,Rankin County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,70.2,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,White,T6,28121,"(32.2698, -89.943383)",2589.0,32.0
40,2015,GA,Barrow County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,71.8,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,White,T6,13013,"(33.99756, -83.711007)",1146.0,31.0
41,2015,TN,Knox County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,103.1,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Female,Race/Ethnicity,Black,T6,47093,"(35.997542, -83.929824)",2013.0,39.0
42,2015,GA,Lowndes County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,78.6,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,White,T6,13185,"(30.832846, -83.262882)",1462.0,31.0
43,2015,FL,Charlotte County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,69.1,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,Black,T6,12015,"(26.905211, -81.890923)",1055.0,30.0
44,2015,IA,Woodbury County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,0.0,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Male,Race/Ethnicity,Hispanic,T6,19193,"(42.390458, -96.05177)",1891.0,16.0
45,2015,ND,Sheridan County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Male,Race/Ethnicity,Hispanic,T6,38083,"(47.576905, -100.348446)",568.0,3.0
46,2015,MO,Morgan County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,77.5,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,NaN,Gender,Overall,Race/Ethnicity,White,T6,29141,"(38.425674, -92.890221)",2127.0,18.0
47,2015,PR,Hatillo Municipio,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Overall,Race/Ethnicity,Hispanic,T6,72065,"(18.409362, -66.796229)",3047.0,NaN
48,2015,LA,Vermilion Parish,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Female,Race/Ethnicity,Hispanic,T6,22113,"(29.854409, -92.316529)",1743.0,22.0
49,2015,GA,Pike County,County,NVSS,Cardiovascular Diseases,Stroke Mortality,NaN,"per 100,000 population","Age-adjusted, Spatially Smoothed, 3-year Avera...",...,Insufficient Data,Gender,Male,Race/Ethnicity,American Indian and Alaskan Native,T6,13231,"(33.091671, -84.385542)",1518.0,31.0

In [52]:
# Using filter to get specific row that has specific key value
df.loc[df["TRIP_METTERS"] == 250 ]

,DATE,FUEL_COST_PER_GAL,TRIP_METTERS,MILES_TRAVELED,GALLONS_USED,FUEL_COST,CO_PAYS_PER_MILE,TOT
2,1/3/2023,3.0,250,50,4,10,0.33,317.33