#### Data Science Project - Machine Leaning.

Capstone: 
Y = (Predicted) Stroke. 
X = (Multiple Factors) Diabetes, Heart Dissease, High Blood Pressure, High Cholesterol, and Obesity 

ML Algorithms = Will be focusing on supervised (multiple linear regression) numeric values.

####### Data provided by https://data.cdc.gov/
Dataset Files:  Diabetes.cvs
Data Measure: 500 Cities: Diagnosed diabetes among adults aged >=18 years

First feature:  Number of diabetes population.

In [1]:

# importing the libraies
import numpy as np
import matplotlib.pyplot as plt
 
import pandas as pd
import seaborn as sns
import math 
#%metplotlib inline #

In [2]:
# Reading, loading  datasets. 

df = pd.read_csv("500_Cities__High_cholesterol.csv" )

In [3]:
df.shape

(29006, 24)

In [4]:
df.head().T

,0,1,2,3,4
Year,2017,2017,2017,2017,2017
StateAbbr,PA,NC,NC,NC,NC
StateDesc,Pennsylvania,North Carolin,North Carolin,North Carolin,North Carolin
CityName,Philadelphia,Cary,Charlotte,Charlotte,Concord
GeographicLevel,Census Tract,Census Tract,Census Tract,Census Tract,Census Tract
DataSource,BRFSS,BRFSS,BRFSS,BRFSS,BRFSS
Category,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes
UniqueID,4260000-42101011800,3710740-37183053601,3712000-37119003105,3712000-37119005524,3714100-37025041902
Measure,High cholesterol among adults aged >=18 Years ...,High cholesterol among adults aged >=18 Years ...,High cholesterol among adults aged >=18 Years ...,High cholesterol among adults aged >=18 Years ...,High cholesterol among adults aged >=18 Years ...
Data_Value_Unit,%,%,%,%,%
DataValueTypeID,CrdPrv,CrdPrv,CrdPrv,CrdPrv,CrdPrv
Data_Value_Type,Crude prevalence,Crude prevalence,Crude prevalence,Crude prevalence,Crude prevalence
Data_Value,34.1,21.8,36.7,27.1,35.0
Low_Confidence_Limit,33.1,21.2,35.7,26.5,34.1
High_Confidence_Limit,35.2,22.4,37.7,27.8,35.9
Data_Value_Footnote_Symbol,NaN,NaN,NaN,NaN,NaN
Data_Value_Footnote,NaN,NaN,NaN,NaN,NaN
PopulationCount,"5,621","5,208","3,480","8,078","4,057"
GeoLocation,"(39.9852890218, -75.2357396856)","(35.8367740061, -78.8996374156)","(35.1322746827, -80.8580889521)","(35.2975067975, -80.7785615388)","(35.4137935177, -80.5926488583)"
CategoryID,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT
MeasureId,HIGHCHOL,HIGHCHOL,HIGHCHOL,HIGHCHOL,HIGHCHOL
CityFIPS,4260000.0,3710740.0,3712000.0,3712000.0,3714100.0
TractFIPS,42101011800.0,37183053601.0,37119003105.0,37119005524.0,37025041902.0
Short_Question_Text,High Cholesterol,High Cholesterol,High Cholesterol,High Cholesterol,High Cholesterol

In [5]:
New_df = df.drop(columns=["Year", "StateDesc",  "GeoLocation", "GeographicLevel" ,"DataSource", "Category", "UniqueID", "Measure", "Data_Value_Unit", "DataValueTypeID", \
"Low_Confidence_Limit", "High_Confidence_Limit", "Data_Value_Footnote", "Data_Value_Footnote_Symbol", "Data_Value_Footnote_Symbol","CategoryID", "TractFIPS", "Short_Question_Text", "DataSource", \
"Category", "UniqueID", "Measure", "Data_Value_Unit","Data_Value",  "DataValueTypeID", "Data_Value_Footnote_Symbol", "MeasureId", "Data_Value_Footnote_Symbol", \
"CategoryID", "TractFIPS","CityFIPS" ,"Short_Question_Text"])

In [6]:
New_df.shape

(29006, 4)

In [7]:
New_df.head()

  StateAbbr      CityName   Data_Value_Type PopulationCount
0        PA  Philadelphia  Crude prevalence           5,621
1        NC          Cary  Crude prevalence           5,208
2        NC     Charlotte  Crude prevalence           3,480
3        NC     Charlotte  Crude prevalence           8,078
4        NC       Concord  Crude prevalence           4,057

In [8]:
New_df = New_df.rename(columns={'StateAbbr':'States', 'CityName':'City', 'Data_Value_Type':'Age-adj_preval','PopulationCount':'PopCountByMM' })

In [9]:
New_df.head()

  States          City    Age-adj_preval PopCountByMM
0     PA  Philadelphia  Crude prevalence        5,621
1     NC          Cary  Crude prevalence        5,208
2     NC     Charlotte  Crude prevalence        3,480
3     NC     Charlotte  Crude prevalence        8,078
4     NC       Concord  Crude prevalence        4,057

In [10]:
# write to a new file.
df_highchol = New_df.query('`Age-adj_preval` == "Age-adjusted prevalence"') 
df_highchol.to_csv("NewDataHighCholesterol.csv")

In [11]:
# Check for NULL/Missing values
print(df_highchol.isna().sum())

States            0
City              1
Age-adj_preval    0
PopCountByMM      0
dtype: int64

In [12]:
# Verify for NULL and dup. values
# No NULL values are found.
df_highchol.loc[df_highchol.duplicated()]

Empty DataFrame
Columns: [States, City, Age-adj_preval, PopCountByMM]
Index: []

In [13]:
#count number of records by each state.
df_highchol['States'].value_counts()

CA    121
TX     47
FL     33
IL     18
MI     16
NC     14
WA     14
CO     14
MA     13
AZ     12
VA     11
GA     11
IN     11
UT      9
OH      9
NY      9
NJ      9
CT      8
OR      8
MO      8
WI      7
MN      7
PA      7
KS      6
IA      6
LA      6
AL      6
TN      6
OK      6
SC      5
AR      5
NV      5
NM      4
RI      4
ID      3
KY      2
NH      2
NE      2
SD      2
MT      2
MS      2
VT      1
WV      1
US      1
AK      1
MD      1
ND      1
DE      1
DC      1
HI      1
ME      1
WY      1
Name: States, dtype: int64

In [14]:


df_highchol.query('`States` == "CA"')

     States         City           Age-adj_preval PopCountByMM
652      CA     Alhambra  Age-adjusted prevalence       83,089
667      CA      Anaheim  Age-adjusted prevalence      336,265
734      CA      Antioch  Age-adjusted prevalence      102,372
774      CA      Alameda  Age-adjusted prevalence       73,812
1208     CA    Daly City  Age-adjusted prevalence      101,123
...     ...          ...                      ...          ...
7423     CA  Westminster  Age-adjusted prevalence       89,701
7598     CA      Visalia  Age-adjusted prevalence      124,442
7667     CA  West Covina  Age-adjusted prevalence      106,098
7676     CA        Vista  Age-adjusted prevalence       93,834
7729     CA     Whittier  Age-adjusted prevalence       85,331

[121 rows x 4 columns]

In [15]:
df_highchol.index

Int64Index([   14,    40,    90,   190,   191,   305,   351,   544,   554,
              652,
            ...
            28462, 28681, 28684, 28810, 28823, 28867, 28933, 28938, 28974,
            29001],
           dtype='int64', length=501)