#### Data Science Project - Machine Leaning.

Capstone: 
Y = (Predicted) Stroke. 
X = (Multiple Factors) Diabetes, Heart Dissease, High Blood Pressure, High Cholesterol, and Obesity 

ML Algorithms = Will be focusing on supervised (multiple linear regression) numeric values.

####### Data provided by https://data.cdc.gov/
Dataset Files:  Diabetes.cvs
Data Measure: 500 Cities: Diagnosed diabetes among adults aged >=18 years

First feature:  Number of diabetes population.

In [10]:

# importing the libraies
import numpy as np
import matplotlib.pyplot as plt
 
import pandas as pd
import seaborn as sns
import math 
#%metplotlib inline #

In [ ]:
%pip install scikit-learn  --upgrade --force
#from sklearn.linear_model import LinearRegression
#from sklearn.model_selection import train_test_split

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [13]:
# Reading, loading  datasets. 

df = pd.read_csv("500_Cities__Obesity.csv" )

In [14]:
df.shape

(29006, 24)

In [15]:
df.head().T

,0,1,2,3,4
Year,2017,2017,2017,2017,2017
StateAbbr,CA,CA,AL,AL,AZ
StateDesc,California,California,Alabama,Alabama,Arizona
CityName,Hayward,Lakewood,Huntsville,Mobile,Avondale
GeographicLevel,City,City,Census Tract,City,Census Tract
DataSource,BRFSS,BRFSS,BRFSS,BRFSS,BRFSS
Category,Unhealthy Behaviors,Unhealthy Behaviors,Unhealthy Behaviors,Unhealthy Behaviors,Unhealthy Behaviors
UniqueID,0633000,0639892,0137000-01089010612,0150000,0404720-04013082027
Measure,Obesity among adults aged >=18 Years,Obesity among adults aged >=18 Years,Obesity among adults aged >=18 Years,Obesity among adults aged >=18 Years,Obesity among adults aged >=18 Years
Data_Value_Unit,%,%,%,%,%
DataValueTypeID,CrdPrv,CrdPrv,CrdPrv,AgeAdjPrv,CrdPrv
Data_Value_Type,Crude prevalence,Crude prevalence,Crude prevalence,Age-adjusted prevalence,Crude prevalence
Data_Value,24.2,22.1,30.3,38.2,30.6
Low_Confidence_Limit,24.1,21.9,29.2,38.0,29.6
High_Confidence_Limit,24.4,22.2,31.5,38.3,31.5
Data_Value_Footnote_Symbol,NaN,NaN,NaN,NaN,NaN
Data_Value_Footnote,NaN,NaN,NaN,NaN,NaN
PopulationCount,"144,186","80,048","2,654","195,111","3,978"
GeoLocation,"(37.6329591551, -122.077051051)","(33.8470531941, -118.122204765)","(34.7636374497, -86.7500225775)","(30.6776248648, -88.1184482714)","(33.4505348518, -112.292540729)"
CategoryID,UNHBEH,UNHBEH,UNHBEH,UNHBEH,UNHBEH
MeasureId,OBESITY,OBESITY,OBESITY,OBESITY,OBESITY
CityFIPS,633000.0,639892.0,137000.0,150000.0,404720.0
TractFIPS,NaN,NaN,1089010612.0,NaN,4013082027.0
Short_Question_Text,Obesity,Obesity,Obesity,Obesity,Obesity

In [16]:
New_df = df.drop(columns=["Year", "StateDesc",  "GeoLocation", "GeographicLevel" ,"DataSource", "Category", "UniqueID", "Measure", "Data_Value_Unit", "DataValueTypeID", \
"Low_Confidence_Limit", "High_Confidence_Limit", "Data_Value_Footnote", "Data_Value_Footnote_Symbol", "Data_Value_Footnote_Symbol","CategoryID", "TractFIPS", "Short_Question_Text", "DataSource", \
"Category", "UniqueID", "Measure", "Data_Value_Unit","Data_Value",  "DataValueTypeID", "Data_Value_Footnote_Symbol", "MeasureId", "Data_Value_Footnote_Symbol", \
"CategoryID", "TractFIPS","CityFIPS" ,"Short_Question_Text"])

In [17]:
New_df.shape

(29006, 4)

In [18]:
New_df.head()

  StateAbbr    CityName          Data_Value_Type PopulationCount
0        CA     Hayward         Crude prevalence         144,186
1        CA    Lakewood         Crude prevalence          80,048
2        AL  Huntsville         Crude prevalence           2,654
3        AL      Mobile  Age-adjusted prevalence         195,111
4        AZ    Avondale         Crude prevalence           3,978

In [19]:
New_df = New_df.rename(columns={'StateAbbr':'States', 'CityName':'City', 'Data_Value_Type':'Age-adj_preval','PopulationCount':'PopCountByMM' })

In [20]:
New_df.head()

  States        City           Age-adj_preval PopCountByMM
0     CA     Hayward         Crude prevalence      144,186
1     CA    Lakewood         Crude prevalence       80,048
2     AL  Huntsville         Crude prevalence        2,654
3     AL      Mobile  Age-adjusted prevalence      195,111
4     AZ    Avondale         Crude prevalence        3,978

In [21]:
# write to a new file.
df_Obesity = New_df.query('`Age-adj_preval` == "Age-adjusted prevalence"') 
#df_diab = New_df.rename(columns={'PopCountByMM':'PopByAgePreval' })
#f_diab.drop(columns=["Age-adj_preval"])
df_Obesity.to_csv("NewDatadf_Obesity_X1.csv")
df_Obesity

#C:\Diff\Python\2023-02-DSI-WE\DollySiharath\MY Project\DataScience Project\NewDatadf_Obesity_X1.csv
#DollySiharath\MY Project\DataScience Project
#C:\Diff\Python\2023-02-DSI-WE\DollySiharath\MY Project\DataScience Project\Input_Output _Files
#DollySiharath\MY Project\DataScience Project\Input_Output _Files

      States        City           Age-adj_preval PopCountByMM
3         AL      Mobile  Age-adjusted prevalence      195,111
6         CA      Corona  Age-adjusted prevalence      152,374
9         CA   Fullerton  Age-adjusted prevalence      135,161
13        CA   San Diego  Age-adjusted prevalence    1,307,402
14        FL  Clearwater  Age-adjusted prevalence      107,685
...      ...         ...                      ...          ...
28845     WA      Yakima  Age-adjusted prevalence       91,067
28880     WI   Green Bay  Age-adjusted prevalence      104,057
28949     WI      Racine  Age-adjusted prevalence       78,860
28972     WI    Waukesha  Age-adjusted prevalence       70,718
28995     WY    Cheyenne  Age-adjusted prevalence       59,466

[501 rows x 4 columns]

In [22]:
# Check for NULL/Missing values
print(df_Obesity.isna().sum())

States            0
City              1
Age-adj_preval    0
PopCountByMM      0
dtype: int64

In [23]:
# Verify for NULL and dup. values
# No NULL values are found.
df_Obesity.loc[df_Obesity.duplicated()]

Empty DataFrame
Columns: [States, City, Age-adj_preval, PopCountByMM]
Index: []

In [24]:
#count number of records by each state.
df_Obesity['States'].value_counts()

CA    121
TX     47
FL     33
IL     18
MI     16
CO     14
NC     14
WA     14
MA     13
AZ     12
IN     11
GA     11
VA     11
UT      9
NY      9
NJ      9
OH      9
CT      8
OR      8
MO      8
MN      7
PA      7
WI      7
TN      6
OK      6
AL      6
LA      6
IA      6
KS      6
AR      5
NV      5
SC      5
RI      4
NM      4
ID      3
NE      2
MT      2
NH      2
KY      2
SD      2
MS      2
VT      1
MD      1
AK      1
WV      1
US      1
HI      1
DC      1
DE      1
ND      1
ME      1
WY      1
Name: States, dtype: int64

In [25]:

#df_diabetes["Texa"] =
df_Obesity.query('`States` == "CA"')

     States         City           Age-adj_preval PopCountByMM
6        CA       Corona  Age-adjusted prevalence      152,374
9        CA    Fullerton  Age-adjusted prevalence      135,161
13       CA    San Diego  Age-adjusted prevalence    1,307,402
26       CA      Visalia  Age-adjusted prevalence      124,442
702      CA      Alameda  Age-adjusted prevalence       73,812
...     ...          ...                      ...          ...
7195     CA      Vallejo  Age-adjusted prevalence      115,942
7199     CA  Victorville  Age-adjusted prevalence      115,903
7351     CA  West Covina  Age-adjusted prevalence      106,098
7368     CA        Vista  Age-adjusted prevalence       93,834
7378     CA     Whittier  Age-adjusted prevalence       85,331

[121 rows x 4 columns]

In [26]:
df_Obesity.index

Int64Index([    3,     6,     9,    13,    14,    15,    26,    29,    79,
              141,
            ...
            28445, 28504, 28774, 28805, 28844, 28845, 28880, 28949, 28972,
            28995],
           dtype='int64', length=501)