#### Data Science Project - Machine Leaning.

Capstone: 
Y = (Predicted) Stroke. 
X = (Multiple Factors) Diabetes, Heart Dissease, High Blood Pressure, High Cholesterol, and Obesity 

ML Algorithms = Will be focusing on supervised (multiple linear regression) numeric values.

####### Data provided by https://data.cdc.gov/
Dataset Files:  Diabetes.cvs
Data Measure: 500 Cities: Diagnosed diabetes among adults aged >=18 years

First feature:  Number of diabetes population.

In [16]:
#importing the libraies
import numpy as np
import matplotlib.pyplot as plt
 
import pandas as pd
import seaborn as sns
import math 
#%metplotlib inline #

In [61]:
# Reading, loading  datasets. 

df = pd.read_csv("500_Cities__High_blood_pressure.csv" )

In [62]:
df.shape

(29006, 24)

In [63]:
df.head().T

,0,1,2,3,4
Year,2017,2017,2017,2017,2017
StateAbbr,AZ,AR,CA,CA,CA
StateDesc,Arizona,Arkansas,California,California,California
CityName,Tucson,Jonesboro,Fairfield,Menifee,Palmdale
GeographicLevel,Census Tract,City,City,Census Tract,City
DataSource,BRFSS,BRFSS,BRFSS,BRFSS,BRFSS
Category,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes
UniqueID,0477000-04019004710,0535710,0623182,0646842-06065042740,0655156
Measure,High blood pressure among adults aged >=18 Years,High blood pressure among adults aged >=18 Years,High blood pressure among adults aged >=18 Years,High blood pressure among adults aged >=18 Years,High blood pressure among adults aged >=18 Years
Data_Value_Unit,%,%,%,%,%
DataValueTypeID,CrdPrv,CrdPrv,CrdPrv,CrdPrv,AgeAdjPrv
Data_Value_Type,Crude prevalence,Crude prevalence,Crude prevalence,Crude prevalence,Age-adjusted prevalence
Data_Value,21.9,33.3,28.7,54.1,28.8
Low_Confidence_Limit,20.9,32.9,28.5,51.7,28.7
High_Confidence_Limit,22.9,33.6,28.9,56.0,29.0
Data_Value_Footnote_Symbol,NaN,NaN,NaN,NaN,NaN
Data_Value_Footnote,NaN,NaN,NaN,NaN,NaN
PopulationCount,"2,138","67,263","105,321","2,017","152,750"
GeoLocation,"(32.2851840496, -110.941404638)","(35.8208121538, -90.6794991686)","(38.2558446343, -122.039303253)","(33.7251014333, -117.197756929)","(34.5944899803, -118.105772328)"
CategoryID,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT
MeasureId,BPHIGH,BPHIGH,BPHIGH,BPHIGH,BPHIGH
CityFIPS,477000.0,535710.0,623182.0,646842.0,655156.0
TractFIPS,4019004710.0,NaN,NaN,6065042740.0,NaN
Short_Question_Text,High Blood Pressure,High Blood Pressure,High Blood Pressure,High Blood Pressure,High Blood Pressure

In [64]:
New_df = df.drop(columns=["Year", "StateDesc",  "GeoLocation", "GeographicLevel" ,"DataSource", "Category", "UniqueID", "Measure", "Data_Value_Unit", "DataValueTypeID", \
"Low_Confidence_Limit", "High_Confidence_Limit", "Data_Value_Footnote", "Data_Value_Footnote_Symbol", "Data_Value_Footnote_Symbol","CategoryID", "TractFIPS", "Short_Question_Text", "DataSource", \
"Category", "UniqueID", "Measure", "Data_Value_Unit","Data_Value",  "DataValueTypeID", "Data_Value_Footnote_Symbol", "MeasureId", "Data_Value_Footnote_Symbol", \
"CategoryID", "TractFIPS","CityFIPS" ,"Short_Question_Text"])

In [65]:
New_df.shape

(29006, 4)

In [66]:
New_df.head()

  StateAbbr   CityName          Data_Value_Type PopulationCount
0        AZ     Tucson         Crude prevalence           2,138
1        AR  Jonesboro         Crude prevalence          67,263
2        CA  Fairfield         Crude prevalence         105,321
3        CA    Menifee         Crude prevalence           2,017
4        CA   Palmdale  Age-adjusted prevalence         152,750

In [67]:
New_df = New_df.rename(columns={'StateAbbr':'States', 'CityName':'City', 'Data_Value_Type':'Age-adj_preval','PopulationCount':'PopCountByMM' })

In [68]:
New_df.head()

  States       City           Age-adj_preval PopCountByMM
0     AZ     Tucson         Crude prevalence        2,138
1     AR  Jonesboro         Crude prevalence       67,263
2     CA  Fairfield         Crude prevalence      105,321
3     CA    Menifee         Crude prevalence        2,017
4     CA   Palmdale  Age-adjusted prevalence      152,750

In [69]:
df_hbp = New_df.query('`Age-adj_preval` == "Age-adjusted prevalence"') 
df_hbp.to_csv("NewDataHighBloodPressure.csv")

In [70]:
# Check for NULL/Missing values
print(df_hbp.isna().sum())

States            0
City              1
Age-adj_preval    0
PopCountByMM      0
dtype: int64

In [71]:
# Verify for NULL and dup. values
# No NULL values are found.
df_hbp.loc[df_hbp.duplicated()]

Empty DataFrame
Columns: [States, City, Age-adj_preval, PopCountByMM]
Index: []

In [72]:
#count number of records by each state.
df_hbp['States'].value_counts()

CA    121
TX     47
FL     33
IL     18
MI     16
NC     14
WA     14
CO     14
MA     13
AZ     12
GA     11
IN     11
VA     11
NY      9
UT      9
NJ      9
OH      9
OR      8
CT      8
MO      8
WI      7
MN      7
PA      7
KS      6
TN      6
IA      6
LA      6
AL      6
OK      6
SC      5
NV      5
AR      5
NM      4
RI      4
ID      3
KY      2
MT      2
NE      2
MS      2
SD      2
NH      2
VT      1
US      1
WV      1
ND      1
AK      1
DE      1
DC      1
HI      1
ME      1
MD      1
WY      1
Name: States, dtype: int64

In [73]:
df_hbp.query('`States` == "CA"')

     States         City           Age-adj_preval PopCountByMM
4        CA     Palmdale  Age-adjusted prevalence      152,750
877      CA      Anaheim  Age-adjusted prevalence      336,265
962      CA      Antioch  Age-adjusted prevalence      102,372
997      CA     Alhambra  Age-adjusted prevalence       83,089
1098     CA      Alameda  Age-adjusted prevalence       73,812
...     ...          ...                      ...          ...
7207     CA      Visalia  Age-adjusted prevalence      124,442
7448     CA     Whittier  Age-adjusted prevalence       85,331
7465     CA        Vista  Age-adjusted prevalence       93,834
7490     CA  Victorville  Age-adjusted prevalence      115,903
7737     CA  West Covina  Age-adjusted prevalence      106,098

[121 rows x 4 columns]

In [74]:
df_hbp.index

Int64Index([    4,     6,    20,    21,    22,    30,   170,   220,   297,
              467,
            ...
            28613, 28693, 28706, 28874, 28892, 28898, 28931, 28943, 28944,
            28949],
           dtype='int64', length=501)