#### Data Science Project - Machine Leaning.

Capstone: 
Y = (Predicted) Stroke. 
X = (Multiple Factors) Diabetes, Heart Dissease, High Blood Pressure, High Cholesterol, and Obesity 

ML Algorithms = Will be focusing on supervised (multiple linear regression) numeric values.

####### Data provided by https://data.cdc.gov/
Dataset Files:  Diabetes.cvs
Data Measure: 500 Cities: Diagnosed diabetes among adults aged >=18 years

First feature:  Number of diabetes population.

In [ ]:

# importing the libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import math 
#%metplotlib inline #

In [ ]:
%pip install scikit-learn  --upgrade --force
#from sklearn.linear_model import LinearRegression
#from sklearn.model_selection import train_test_split

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
# Reading, loading  datasets. 

df = pd.read_csv("500_Cities__Coronary_heart_disease.csv" )

In [16]:
df.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'CityName', 'GeographicLevel',
       'DataSource', 'Category', 'UniqueID', 'Measure', 'Data_Value_Unit',
       'DataValueTypeID', 'Data_Value_Type', 'Data_Value',
       'Low_Confidence_Limit', 'High_Confidence_Limit',
       'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'PopulationCount',
       'GeoLocation', 'CategoryID', 'MeasureId', 'CityFIPS', 'TractFIPS',
       'Short_Question_Text'],
      dtype='object')

In [3]:
df.shape

(29006, 24)

In [4]:
df.head().T

,0,1,2,3,4
Year,2017,2017,2017,2017,2017
StateAbbr,CA,AL,AZ,AZ,CA
StateDesc,California,Alabama,Arizona,Arizona,California
CityName,Hayward,Huntsville,Chandler,Surprise,Bellflower
GeographicLevel,City,City,City,City,City
DataSource,BRFSS,BRFSS,BRFSS,BRFSS,BRFSS
Category,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes,Health Outcomes
UniqueID,0633000,0137000,0412000,0471510,0604982
Measure,Coronary heart disease among adults aged >=18 ...,Coronary heart disease among adults aged >=18 ...,Coronary heart disease among adults aged >=18 ...,Coronary heart disease among adults aged >=18 ...,Coronary heart disease among adults aged >=18 ...
Data_Value_Unit,%,%,%,%,%
DataValueTypeID,AgeAdjPrv,CrdPrv,CrdPrv,CrdPrv,AgeAdjPrv
Data_Value_Type,Age-adjusted prevalence,Crude prevalence,Crude prevalence,Crude prevalence,Age-adjusted prevalence
Data_Value,4.8,6.7,3.8,5.9,5.3
Low_Confidence_Limit,4.7,6.6,3.8,5.8,5.2
High_Confidence_Limit,4.8,6.8,3.9,6.1,5.4
Data_Value_Footnote_Symbol,NaN,NaN,NaN,NaN,NaN
Data_Value_Footnote,NaN,NaN,NaN,NaN,NaN
PopulationCount,"144,186","180,105","236,123","117,517","76,616"
GeoLocation,"(37.6329591551, -122.077051051)","(34.6989692671, -86.6387042882)","(33.28318981, -111.852210033)","(33.6803835177, -112.452218439)","(33.8880417923, -118.127100236)"
CategoryID,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT,HLTHOUT
MeasureId,CHD,CHD,CHD,CHD,CHD
CityFIPS,633000.0,137000.0,412000.0,471510.0,604982.0
TractFIPS,NaN,NaN,NaN,NaN,NaN
Short_Question_Text,Coronary Heart Disease,Coronary Heart Disease,Coronary Heart Disease,Coronary Heart Disease,Coronary Heart Disease

In [5]:
New_df = df.drop(columns=["Year", "StateDesc",  "GeoLocation", "GeographicLevel" ,"DataSource", "Category", "UniqueID", "Measure", "Data_Value_Unit", "DataValueTypeID", \
"Low_Confidence_Limit", "High_Confidence_Limit", "Data_Value_Footnote", "Data_Value_Footnote_Symbol", "Data_Value_Footnote_Symbol","CategoryID", "TractFIPS", "Short_Question_Text", "DataSource", \
"Category", "UniqueID", "Measure", "Data_Value_Unit","Data_Value",  "DataValueTypeID", "Data_Value_Footnote_Symbol", "MeasureId", "Data_Value_Footnote_Symbol", \
"CategoryID", "TractFIPS","CityFIPS" ,"Short_Question_Text"])

In [6]:
New_df.shape

(29006, 4)

In [7]:
New_df.head()

  StateAbbr    CityName          Data_Value_Type PopulationCount
0        CA     Hayward  Age-adjusted prevalence         144,186
1        AL  Huntsville         Crude prevalence         180,105
2        AZ    Chandler         Crude prevalence         236,123
3        AZ    Surprise         Crude prevalence         117,517
4        CA  Bellflower  Age-adjusted prevalence          76,616

In [8]:
New_df = New_df.rename(columns={'StateAbbr':'States', 'CityName':'City', 'Data_Value_Type':'Age-adj_preval','PopulationCount':'PopCountByMM' })

In [9]:
New_df.head()

  States        City           Age-adj_preval PopCountByMM
0     CA     Hayward  Age-adjusted prevalence      144,186
1     AL  Huntsville         Crude prevalence      180,105
2     AZ    Chandler         Crude prevalence      236,123
3     AZ    Surprise         Crude prevalence      117,517
4     CA  Bellflower  Age-adjusted prevalence       76,616

In [10]:
# Writing to a new file.
df_cor = New_df.query('`Age-adj_preval` == "Age-adjusted prevalence"') 
df_cor.to_csv("NewDataCoronaryHeartDise.csv")

In [11]:
# Check for NULL/Missing values
print(df_cor.isna().sum())

States            0
City              1
Age-adj_preval    0
PopCountByMM      0
dtype: int64

In [12]:
# Verify for NULL and dup. values
# No NULL values are found.
df_cor.loc[df_cor.duplicated()]

Empty DataFrame
Columns: [States, City, Age-adj_preval, PopCountByMM]
Index: []

In [13]:
#count number of records by each state.
df_cor['States'].value_counts()

CA    121
TX     47
FL     33
IL     18
MI     16
WA     14
CO     14
NC     14
MA     13
AZ     12
VA     11
GA     11
IN     11
OH      9
UT      9
NY      9
NJ      9
OR      8
MO      8
CT      8
PA      7
WI      7
MN      7
TN      6
LA      6
OK      6
KS      6
IA      6
AL      6
NV      5
AR      5
SC      5
RI      4
NM      4
ID      3
NE      2
MT      2
NH      2
MS      2
SD      2
KY      2
VT      1
WV      1
HI      1
AK      1
ND      1
DE      1
DC      1
US      1
MD      1
ME      1
WY      1
Name: States, dtype: int64

In [14]:

#df_diabetes["Texa"] =
df_cor.query('`States` == "CA"')

     States         City           Age-adj_preval PopCountByMM
0        CA      Hayward  Age-adjusted prevalence      144,186
4        CA   Bellflower  Age-adjusted prevalence       76,616
566      CA      Antioch  Age-adjusted prevalence      102,372
729      CA      Alameda  Age-adjusted prevalence       73,812
801      CA     Alhambra  Age-adjusted prevalence       83,089
...     ...          ...                      ...          ...
7523     CA     Whittier  Age-adjusted prevalence       85,331
7558     CA  West Covina  Age-adjusted prevalence      106,098
7570     CA  Victorville  Age-adjusted prevalence      115,903
7664     CA      Visalia  Age-adjusted prevalence      124,442
7713     CA      Vallejo  Age-adjusted prevalence      115,942

[121 rows x 4 columns]

In [15]:
df_cor.index

Int64Index([    0,     4,     9,    16,    28,    42,    49,   120,   157,
              211,
            ...
            28547, 28608, 28650, 28703, 28745, 28766, 28848, 28946, 28953,
            28998],
           dtype='int64', length=501)