# Pandas Basics

In [5]:
children = ["Andrew","Laura","Joe"]
lol_children = [[c, len(c)]  for c in children]
lol_children

[['Andrew', 6], ['Laura', 5], ['Joe', 3]]

In [ ]:
# may need to run on download from python.org
!pip install pandas

In [6]:
# 1. DataFrame from List Of Lists - row
import pandas as pd
df_lol_children = pd.DataFrame(lol_children,columns = ["child","charlen"])
df_lol_children

    child  charlen
0  Andrew        6
1   Laura        5
2     Joe        3

In [7]:

len_char = [len(c) for c in children]
print(len_char)
d_children = {"child": children, "charlen": len_char}
print(d_children)

[6, 5, 3]
{'child': ['Andrew', 'Laura', 'Joe'], 'charlen': [6, 5, 3]}

In [8]:
#2. DataFrame from dictionary of lists - column
df_d_children = pd.DataFrame(d_children)
df_d_children

    child  charlen
0  Andrew        6
1   Laura        5
2     Joe        3

In [9]:
d_children_v2 =[ {"child": c, "charlen":  len(c)} for c in children ]
d_children_v2

[{'child': 'Andrew', 'charlen': 6},
 {'child': 'Laura', 'charlen': 5},
 {'child': 'Joe', 'charlen': 3}]

In [10]:
# 3. DataFrame from List Of Dictionaries - row
df_d_children_2 = pd.DataFrame(d_children_v2)
df_d_children_2

    child  charlen
0  Andrew        6
1   Laura        5
2     Joe        3

In [11]:
type(df_d_children)

pandas.core.frame.DataFrame

In [12]:
df_d_children?

Type:        DataFrame
String form:
    child  charlen
0  Andrew        6
1   Laura        5
2     Joe        3
Length:      3
File:        c:\users\andre\appdata\local\programs\python\python311\lib\site-packages\pandas\core\frame.py
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index.

    .. versionchanged:: 0.25.0
       If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

In [14]:
list(df_d_children.columns)

['child', 'charlen']

In [15]:
df_d_children.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   child    3 non-null      object
 1   charlen  3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

## Get the data

In [23]:
#poll_url = 'http://projects.fivethirtyeight.com/general-model/president_general_polls_2016.csv'
poll_url = 'H:\president_general_polls_2016.csv'

polls = pd.read_csv(poll_url)

In [20]:
type(polls)

pandas.core.frame.DataFrame

In [24]:
len(list(polls.columns))

27

In [42]:
polls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             12624 non-null  int64
 1   branch            12624 non-null  object
 2   type              12624 non-null  object
 3   matchup           12624 non-null  object
 4   forecastdate      12624 non-null  object
 5   state             12624 non-null  object
 6   startdate         12624 non-null  datetime64[ns]
 7   enddate           12624 non-null  datetime64[ns]
 8   pollster          12624 non-null  object
 9   grade             11337 non-null  object
 10  samplesize        12621 non-null  float64
 11  population        12624 non-null  object
 12  poll_wt           12624 non-null  float64
 13  rawpoll_clinton   12624 non-null  float64
 14  rawpoll_trump     12624 non-null  float64
 15  rawpoll_johnson   8397 non-null   float64
 16  rawpoll_mcmullin  90 non-null     float64
 17  adjpoll_clinton   12624 non-null  float64
 18  adjpoll_trump     12624 non-null  float64
 19  adjpoll_johnson   8397 non-null   float64
 20  adjpoll_mcmullin  90 non-null     float64
 21  multiversions     36 non-null     object
 22  url               12621 non-null  object
 23  poll_id           12624 non-null  int64
 24  question_id       12624 non-null  int64
 25  createddate       12624 non-null  object
 26  timestamp         12624 non-null  object
dtypes: datetime64[ns](2), float64(10), int64(3), object(12)
memory usage: 2.6+ MB

In [27]:
df_d_children

    child  charlen
0  Andrew        6
1   Laura        5
2     Joe        3

In [28]:
df_d_children.T

              0      1    2
child    Andrew  Laura  Joe
charlen       6      5    3

In [30]:
polls.describe().T

,count,mean,std,min,25%,50%,75%,max
cycle,12624.0,2016.000000,0.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
samplesize,12621.0,1148.216068,2630.647790,35.000000,447.000000,772.000000,1237.000000,84292.000000
poll_wt,12624.0,0.255431,0.669326,0.000000,0.000358,0.008172,0.086735,8.720654
rawpoll_clinton,12624.0,41.990860,7.727792,11.040000,38.000000,43.000000,46.200000,88.000000
rawpoll_trump,12624.0,39.828710,7.877327,4.000000,35.000000,40.000000,45.000000,68.000000
rawpoll_johnson,8397.0,7.381740,2.959274,0.000000,5.400000,7.000000,9.000000,25.000000
rawpoll_mcmullin,90.0,24.004000,5.638641,9.000000,22.000000,25.000000,28.000000,31.000000
adjpoll_clinton,12624.0,43.323005,7.095235,17.064950,40.210697,44.148045,46.908830,86.772180
adjpoll_trump,12624.0,42.667719,6.948256,4.372936,38.445588,42.716265,46.313520,72.437390
adjpoll_johnson,8397.0,4.655091,2.472636,-3.677883,3.136837,4.375392,5.761469,20.366840
adjpoll_mcmullin,90.0,24.511497,5.174286,11.028320,22.814548,25.136030,28.067610,31.583810
poll_id,12624.0,45910.899477,2864.536271,35362.000000,45151.750000,46384.500000,47741.250000,48922.000000
question_id,12624.0,71591.326046,4699.401001,47244.000000,69548.500000,72516.500000,74724.250000,76636.000000

In [43]:
polls.describe(datetime_is_numeric=True).T

,count,mean,min,25%,50%,75%,max,std
cycle,12624.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,0.0
startdate,12624,2016-08-31 01:50:11.406844160,2015-11-06 00:00:00,2016-08-10 00:00:00,2016-09-23 00:00:00,2016-10-20 00:00:00,2016-11-06 00:00:00,NaN
enddate,12624,2016-09-06 14:23:02.509505792,2015-11-08 00:00:00,2016-08-21 00:00:00,2016-09-30 00:00:00,2016-10-28 00:00:00,2016-11-07 00:00:00,NaN
samplesize,12621.0,1148.216068,35.0,447.0,772.0,1237.0,84292.0,2630.64779
poll_wt,12624.0,0.255431,0.0,0.000358,0.008172,0.086735,8.720654,0.669326
rawpoll_clinton,12624.0,41.99086,11.04,38.0,43.0,46.2,88.0,7.727792
rawpoll_trump,12624.0,39.82871,4.0,35.0,40.0,45.0,68.0,7.877327
rawpoll_johnson,8397.0,7.38174,0.0,5.4,7.0,9.0,25.0,2.959274
rawpoll_mcmullin,90.0,24.004,9.0,22.0,25.0,28.0,31.0,5.638641
adjpoll_clinton,12624.0,43.323005,17.06495,40.210697,44.148045,46.90883,86.77218,7.095235
adjpoll_trump,12624.0,42.667719,4.372936,38.445588,42.716265,46.31352,72.43739,6.948256
adjpoll_johnson,8397.0,4.655091,-3.677883,3.136837,4.375392,5.761469,20.36684,2.472636
adjpoll_mcmullin,90.0,24.511497,11.02832,22.814548,25.13603,28.06761,31.58381,5.174286
poll_id,12624.0,45910.899477,35362.0,45151.75,46384.5,47741.25,48922.0,2864.536271
question_id,12624.0,71591.326046,47244.0,69548.5,72516.5,74724.25,76636.0,4699.401001

In [35]:
5.174286/24.511497

0.2110962867751407

In [36]:
2630.647790/1148.216068

2.2910738347201045

In [ ]:
#CV = coefficent of variance = stdev/mean < 5%

In [32]:
polls.describe(include="datetime").T

ValueError: No objects to concatenate

In [34]:
polls.describe(include="O")

,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,population,multiversions,url,createddate,timestamp
count,12624,12624,12624,12624,12624,12624,12624,12624,11337,12624,36,12621,12624,12624
unique,1,3,1,1,57,352,345,196,10,4,1,1304,222,3
top,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,10/20/2016,11/6/2016,Ipsos,A-,lv,*,https://datastudio.google.com/u/0/#/org//repor...,11/7/16,09:35:33 8 Nov 2016
freq,12624,4208,12624,12624,3318,480,588,2757,3255,11181,36,1407,804,4208

In [38]:
#SELECT startdate, count(*) from polls group by startdate
len(polls.samplesize.value_counts())

1766

In [ ]:
polls

In [39]:
polls["startdate"] = pd.to_datetime(polls["startdate"])

In [40]:
polls["enddate"] = pd.to_datetime(polls["enddate"])

In [45]:
polls.head(5)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,2016-11-03,2016-11-06,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,2016-11-01,2016-11-07,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,2016-11-02,2016-11-06,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,2016-11-04,2016-11-07,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,2016-11-03,2016-11-06,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

In [46]:
polls["forecastdate"] = pd.to_datetime(polls["forecastdate"])

In [ ]:
polls.info()

In [47]:
polls.columns

Index(['cycle', 'branch', 'type', 'matchup', 'forecastdate', 'state',
       'startdate', 'enddate', 'pollster', 'grade', 'samplesize', 'population',
       'poll_wt', 'rawpoll_clinton', 'rawpoll_trump', 'rawpoll_johnson',
       'rawpoll_mcmullin', 'adjpoll_clinton', 'adjpoll_trump',
       'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'url',
       'poll_id', 'question_id', 'createddate', 'timestamp'],
      dtype='object')

In [48]:
polls.dtypes

cycle                        int64
branch                      object
type                        object
matchup                     object
forecastdate        datetime64[ns]
state                       object
startdate           datetime64[ns]
enddate             datetime64[ns]
pollster                    object
grade                       object
samplesize                 float64
population                  object
poll_wt                    float64
rawpoll_clinton            float64
rawpoll_trump              float64
rawpoll_johnson            float64
rawpoll_mcmullin           float64
adjpoll_clinton            float64
adjpoll_trump              float64
adjpoll_johnson            float64
adjpoll_mcmullin           float64
multiversions               object
url                         object
poll_id                      int64
question_id                  int64
createddate                 object
timestamp                   object
dtype: object

In [49]:
polls.tail()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
12619,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,New Hampshire,2016-07-09,2016-07-18,University of New Hampshire,B+,...,40.24983,43.04717,6.924110,NaN,NaN,https://cola.unh.edu/sites/cola.unh.edu/files/...,44650,68189,7/21/16,09:14:14 8 Nov 2016
12620,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Wisconsin,2016-10-21,2016-11-02,Ipsos,A-,...,46.54218,38.96884,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,48259,75560,11/3/16,09:14:14 8 Nov 2016
12621,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,New York,2016-08-07,2016-08-10,Siena College,A,...,53.83622,32.47939,3.881193,NaN,NaN,https://www.siena.edu/assets/files/news/SNY081...,44852,68743,8/15/16,09:14:14 8 Nov 2016
12622,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Virginia,2016-09-30,2016-10-06,Ipsos,A-,...,49.57558,39.96954,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,46675,72969,10/10/16,09:14:14 8 Nov 2016
12623,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Wisconsin,2016-06-09,2016-06-12,Marquette University,A,...,46.40999,39.19839,NaN,NaN,NaN,https://law.marquette.edu/poll/2016/06/15/new-...,44341,66966,6/15/16,09:14:14 8 Nov 2016

## Sort the data

In [53]:
polls.sample(frac=.001)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
262,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,2016-11-08,West Virginia,2016-11-01,2016-11-07,SurveyMonkey,C-,...,27.59833,55.33043,4.692430,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48908,76598,11/8/16,09:35:33 8 Nov 2016
7685,2016,President,now-cast,Clinton vs. Trump vs. Johnson,2016-11-08,Minnesota,2016-08-10,2016-08-16,Google Consumer Surveys,B,...,48.30452,35.80421,4.827812,NaN,NaN,https://drive.google.com/drive/u/0/folders/0B2...,45613,70998,9/9/16,09:24:53 8 Nov 2016
9784,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Alaska,2016-10-28,2016-11-03,SurveyMonkey,C-,...,33.68383,45.90326,8.397103,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48270,75637,11/4/16,09:14:14 8 Nov 2016
12590,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Alabama,2016-09-30,2016-10-13,Ipsos,A-,...,37.21752,54.74955,NaN,NaN,NaN,http://reuters.com/statesofthenation/,46817,73263,10/15/16,09:14:14 8 Nov 2016
9153,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Michigan,2016-11-03,2016-11-03,Mitchell Research & Communications,D,...,44.86445,40.02137,7.373952,NaN,NaN,http://www.fox2detroit.com/news/local-news/215...,48486,75986,11/6/16,09:14:14 8 Nov 2016
11375,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Mississippi,2016-08-31,2016-09-06,Google Consumer Surveys,B,...,34.37394,61.62885,1.315774,NaN,NaN,https://drive.google.com/drive/u/0/folders/0B2...,45464,70782,9/9/16,09:14:14 8 Nov 2016
6070,2016,President,now-cast,Clinton vs. Trump vs. Johnson,2016-11-08,Connecticut,2016-10-27,2016-11-02,SurveyMonkey,C-,...,50.69333,38.05447,3.269698,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48135,75404,11/3/16,09:24:53 8 Nov 2016
1614,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,2016-11-08,South Dakota,2016-10-26,2016-11-01,SurveyMonkey,C-,...,25.72533,52.22225,15.145220,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48062,75191,11/2/16,09:35:33 8 Nov 2016
672,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,2016-11-08,U.S.,2016-10-30,2016-11-01,YouGov,B,...,46.94868,43.42593,4.889163,NaN,NaN,https://today.yougov.com/news/2016/11/02/post-...,48082,75219,11/2/16,09:35:33 8 Nov 2016
9703,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Arizona,2016-08-25,2016-08-27,MBQF,C+,...,41.37494,42.99046,4.189418,NaN,NaN,http://email.connectstrategic.com/t/j-73630F4B...,45048,69102,8/29/16,09:14:14 8 Nov 2016
1345,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,2016-11-08,Wyoming,2016-10-26,2016-11-01,SurveyMonkey,C-,...,19.72460,62.21990,5.145224,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48071,75200,11/2/16,09:35:33 8 Nov 2016
9946,2016,President,polls-only,Clinton vs. Trump vs. Johnson,2016-11-08,Florida,2016-09-28,2016-09-29,Opinion Savvy/InsiderAdvantage,C-,...,47.34288,48.74633,0.732492,NaN,NaN,http://opinionsavvy.com/2016/09/30/poll-clinto...,46304,72387,9/30/16,09:14:14 8 Nov 2016
741,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,2016-11-08,Pennsylvania,2016-10-25,2016-10-30,Gravis Marketing,B-,...,47.01987,44.37854,3.077624,NaN,NaN,http://www.breitbart.com/2016-presidential-rac...,47867,74909,10/31/16,09:35:33 8 Nov 2016

In [50]:
#polls[[enddate]].max()
polls.enddate.max()

enddate   2016-11-07
dtype: datetime64[ns]

In [ ]:
polls.sort_values('enddate', ascending=False, inplace=True)
polls.head()

## Use lists, slices, tuples, and dictionary objects

### A list

In [54]:
# columns=['cycle','branch','matchup','forecastdate'], inplace=True
dict_input = {"columns":['cycle','branch','matchup','forecastdate'], "inplace":True}
polls.drop(**dict_input)
polls.head(2)

,type,state,startdate,enddate,pollster,grade,samplesize,population,poll_wt,rawpoll_clinton,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,polls-plus,U.S.,2016-11-03,2016-11-06,ABC News/Washington Post,A+,2220.0,lv,8.720654,47.00,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,polls-plus,U.S.,2016-11-01,2016-11-07,Google Consumer Surveys,B,26574.0,lv,7.628472,38.03,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016

### A dictionary, ranges and comprehension

In [55]:
polls = polls.rename(columns={'adjpoll_clinton':'Clinton',
                      'adjpoll_trump':'Trump'})
polls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   type              12624 non-null  object
 1   state             12624 non-null  object
 2   startdate         12624 non-null  datetime64[ns]
 3   enddate           12624 non-null  datetime64[ns]
 4   pollster          12624 non-null  object
 5   grade             11337 non-null  object
 6   samplesize        12621 non-null  float64
 7   population        12624 non-null  object
 8   poll_wt           12624 non-null  float64
 9   rawpoll_clinton   12624 non-null  float64
 10  rawpoll_trump     12624 non-null  float64
 11  rawpoll_johnson   8397 non-null   float64
 12  rawpoll_mcmullin  90 non-null     float64
 13  Clinton           12624 non-null  float64
 14  Trump             12624 non-null  float64
 15  adjpoll_johnson   8397 non-null   float64
 16  adjpoll_mcmullin  90 non-null     float64
 17  multiversions     36 non-null     object
 18  url               12621 non-null  object
 19  poll_id           12624 non-null  int64
 20  question_id       12624 non-null  int64
 21  createddate       12624 non-null  object
 22  timestamp         12624 non-null  object
dtypes: datetime64[ns](2), float64(10), int64(2), object(9)
memory usage: 2.2+ MB

In [56]:
len(polls)

12624

In [57]:
num = [f for f in range(0,12624)]
num

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [58]:
num[0:100]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

### Two slices

In [61]:
foo = polls.loc[0:100:10,'state':'grade'].index
foo

RangeIndex(start=0, stop=101, step=10)

In [62]:
",".join([str(f) for f in foo])

'0,10,20,30,40,50,60,70,80,90,100'